apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-l0qx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-l0qx@sha256:4796c0a53e0be3e34aff22f48c9ad4843d510ed46d57ce0233ce988f97adfcc5
        name: my-nodejs
        resources: {}
status: {}
